[tool.black]
exclude = '\.venv/|interface2050.py'
[tool.isort]
known_third_party = ["anvil", "i18n", "interface2050", "numpy", "openpyxl", "plotly", "pytest", "yaml"]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
skip_glob = "tests/test_model/interface2050.py"
